#!/usr/bin/env python3

icecream= ["flavors", "salty"]
northerntrust= ["Alex","Andrew","Dave","Julia","Kurt","Marlon","Roger","Seth","Tim","Viq"]

icecream.append(99)
print (icecream)

index = int(input ("Enter a digit between 0 and 9: \n>"))

#print (icecream[-1], "and " northerntrust[index] "chooses to be "icecream[1])
print (icecream[-1])
print (northernturst[index])
print (icecream[1])


